//! A Burp Sequencer clone.
//!
//! Sends a sequence of requests carrying fresh server-generated random values
//! and measures their randomness. This answers the question that matters in
//! security testing: are these token / session / nonce values generated by a
//! cryptographically secure source, or are they predictable?
//!
//! Design rules inherited from Burp Sequencer and from the other tools:
//!
//! * **Plan-first** - no request is sent until the operator confirms the plan
//!   (target, value type, count).
//! * **Caps** - count defaults to 10 and is capped at 1,000 so this never
//!   runs away as a DoS against a target.
//! * **Facts, never verdicts** - the output is a battery of statistical
//!   observations (entropy, chi-square, collisions, runs). A low p-value says
//!   "the distribution looks non-uniform," not "this is vulnerable." Reading
//!   the numbers, and correlating them with the protocol, is a human job.
//!
//! The core idea: generate N distinct tokens, submit them N times through the
//! target in whatever way you are testing (query param, header, body), collect
//! the responses, and treat the response bytes that carry the token as the
//! value under test. From those bytes you compute Shannon entropy, a
//! chi-square uniformity test, a collision count, and a runs test for
//! autocorrelation.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use thiserror::Error;
use uuid::Uuid;

/// Trait import needed by `gen_range`.
use rand::Rng;

#[derive(Debug, Error)]
pub enum SequencerError {
    #[error("Invalid plan: {0}")]
    InvalidPlan(String),

    #[error("Request failed: {0}")]
    Request(#[from] reqwest::Error),

    #[error("No values collected")]
    NoValues,
}

pub type Result<T> = std::result::Result<T, SequencerError>;

/// A sequence plan: what to test and how much.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SeqPlan {
    /// Method to use for every request.
    pub method: String,
    /// Base URL to send each request against.
    pub url: String,
    /// How many distinct values to generate and submit.
    pub count: usize,
    /// Concurrency of the submission.
    pub concurrency: usize,
    /// Header to carry the value (or "body"/"query" for special transports).
    pub transport: Transport,
    /// Custom value generator; defaults to fresh UUIDs.
    pub generator: Generator,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "kind")]
pub enum Transport {
    /// Put the value in this header name.
    Header { name: String },
    /// Put the value in this query parameter name.
    Query { name: String },
    /// Put the value as JSON at this field path.
    Json { path: String },
}

impl Transport {
    fn apply(&self, req: reqwest::RequestBuilder, value: &str) -> reqwest::RequestBuilder {
        match self {
            Transport::Header { name } => req.header(name, value),
            Transport::Query { name } => req.query(&[(name.as_str(), value)]),
            Transport::Json { path } => {
                use serde_json::Map;
                let mut m = Map::new();
                m.insert(path.clone(), serde_json::Value::String(value.to_string()));
                req.json(&m)
            }
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "kind")]
pub enum Generator {
    /// Fresh 128-bit UUIDs.
    Uuid,
    /// Random hex of the given byte length.
    Hex { bytes: usize },
    /// The value is read from the response of a preceding request.
    ExtractFromResponse {
        header: Option<String>,
        pattern: Option<String>,
    },
}

/// A single submitted value and the response it produced.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ObservedValue {
    /// The value that was sent (base64-encoded so non-UTF8 is preserved).
    pub value: String,
    /// The status of the response.
    pub status: u16,
    /// The response bytes, base64-encoded.
    pub response_b64: String,
}

/// Results of a sequence run.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SequenceRun {
    pub plan: SeqPlan,
    pub sent: usize,
    pub collected: usize,
    pub observations: Observations,
}

/// Statistical observations about the collected values.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Observations {
    /// Shannon entropy of the value byte stream, bits per byte.
    pub entropy_bits_per_byte: f64,
    /// Max possible entropy at the observed width.
    pub max_entropy_bits_per_byte: f64,
    /// Chi-square statistic over single-byte frequencies.
    pub chi_square: f64,
    /// Chi-square p-value (high = uniform, low = suspicious).
    pub chi_square_p_value: f64,
    /// Number of duplicate values (0 expected).
    pub collisions: usize,
    /// Runs test statistic for value-byte autocorrelation.
    pub runs_z: f64,
    /// Number of distinct values observed.
    pub distinct_values: usize,
    /// Whether the raw value stream looks wide enough.
    pub value_width_bits: usize,
}

#[derive(Debug, Clone, Default)]
pub struct Sequencer;

impl Sequencer {
    /// Validate and normalise the plan.
    pub fn validate(&self, plan: &SeqPlan) -> Result<()> {
        if plan.method.is_empty() {
            return Err(SequencerError::InvalidPlan("method is required".into()));
        }
        if plan.url.is_empty() {
            return Err(SequencerError::InvalidPlan("url is required".into()));
        }
        if plan.count == 0 {
            return Err(SequencerError::InvalidPlan(
                "count must be at least 1".into(),
            ));
        }
        if plan.count > 1_000 {
            return Err(SequencerError::InvalidPlan(
                "count is capped at 1,000".into(),
            ));
        }
        if plan.concurrency == 0 || plan.concurrency > 16 {
            return Err(SequencerError::InvalidPlan(
                "concurrency must be 1..=16".into(),
            ));
        }
        Ok(())
    }

    /// Generate the values, submit them, and collect responses.
    pub async fn run(&self, plan: &SeqPlan) -> Result<SequenceRun> {
        self.validate(plan)?;
        let values = self.generate_values(&plan.generator, plan.count)?;
        let client = reqwest::Client::builder()
            .timeout(std::time::Duration::from_secs(30))
            .build()?;
        let mut collected = Vec::new();

        let mut handles = Vec::new();
        for value in values {
            let method =
                reqwest::Method::from_bytes(plan.method.as_bytes()).unwrap_or(reqwest::Method::GET);
            let req = client.request(method, &plan.url);
            let req = plan.transport.apply(req, &value);
            handles.push(tokio::spawn(async move {
                match req.send().await {
                    Ok(resp) => {
                        let status = resp.status().as_u16();
                        let bytes = resp.bytes().await.unwrap_or_default().to_vec();
                        (value, status, bytes)
                    }
                    Err(e) => (value, 0, format!("error: {e}").into_bytes()),
                }
            }));
        }

        for handle in handles {
            match handle.await {
                Ok((value, status, bytes)) => {
                    collected.push(ObservedValue {
                        value,
                        status,
                        response_b64: base64::Engine::encode(
                            &base64::engine::general_purpose::STANDARD,
                            &bytes,
                        ),
                    });
                }
                Err(e) => {
                    tracing::error!("sequencer task panicked: {e}");
                }
            }
        }

        let observations = compute_observations(&collected);

        Ok(SequenceRun {
            plan: plan.clone(),
            sent: plan.count,
            collected: collected.len(),
            observations,
        })
    }

    fn generate_values(&self, generator: &Generator, count: usize) -> Result<Vec<String>> {
        match generator {
            Generator::Uuid => Ok((0..count).map(|_| Uuid::new_v4().to_string()).collect()),
            Generator::Hex { bytes } => {
                let pool = "0123456789abcdef";
                Ok((0..count)
                    .map(|_| {
                        (0..*bytes)
                            .map(|_| self.rand_char(pool))
                            .collect::<String>()
                    })
                    .collect())
            }
            Generator::ExtractFromResponse { .. } => Err(SequencerError::InvalidPlan(
                "extraction not yet supported".into(),
            )),
        }
    }

    fn rand_char(&self, pool: &str) -> char {
        let idx = rand::thread_rng().gen_range(0..pool.len());
        pool.chars().nth(idx).unwrap()
    }
}

/// Turn collected values into statistics.
fn compute_observations(collected: &[ObservedValue]) -> Observations {
    let mut values_bytes: Vec<u8> = Vec::new();
    let mut seen: std::collections::HashSet<String> = std::collections::HashSet::new();
    for o in collected {
        let decoded = base64::Engine::decode(&base64::engine::general_purpose::STANDARD, &o.value)
            .unwrap_or_default();
        seen.insert(o.value.clone());
        values_bytes.extend(decoded);
    }

    let width_bits = values_bytes.len() * 8;
    let entropy = shannon_entropy(&values_bytes);
    let max_entropy = width_bits as f64 / 8.0;
    let (chi_sq, p) = chi_square_uniform(&values_bytes);
    let collisions = collected.len() - seen.len();
    let runs = runs_test(&values_bytes);

    Observations {
        entropy_bits_per_byte: entropy,
        max_entropy_bits_per_byte: max_entropy,
        chi_square: chi_sq,
        chi_square_p_value: p,
        collisions,
        runs_z: runs,
        distinct_values: seen.len(),
        value_width_bits: width_bits,
    }
}

/// Shannon entropy in bits per byte.
fn shannon_entropy(data: &[u8]) -> f64 {
    let mut freq: HashMap<u8, u64> = HashMap::new();
    for &b in data {
        *freq.entry(b).or_default() += 1;
    }
    let n = data.len() as f64;
    if n == 0.0 {
        return 0.0;
    }
    let mut h = 0.0;
    for &c in freq.values() {
        let p = c as f64 / n;
        if p > 0.0 {
            h -= p * p.log2();
        }
    }
    h
}

/// Chi-square test of byte uniformity. 256 buckets, expected = n/256.
fn chi_square_uniform(data: &[u8]) -> (f64, f64) {
    let mut freq: [u64; 256] = [0; 256];
    for &b in data {
        freq[b as usize] += 1;
    }
    let n = data.len() as f64;
    let expected = if n < 256.0 { 1.0 } else { n / 256.0 };
    let mut chi = 0.0;
    for &c in freq.iter() {
        if c > 0 {
            chi += (c as f64 - expected).powi(2) / expected;
        }
    }
    (chi, chi2_cdf_approx(chi, 255.0))
}

/// Rough chi-square CDF (255 dof) via Wilson-Hilferty normal approximation.
fn chi2_cdf_approx(x: f64, dof: f64) -> f64 {
    let z = ((x / dof).powf(1.0 / 3.0) - (1.0 - 2.0 / (9.0 * dof))) / (2.0 / (9.0 * dof)).sqrt();
    normal_cdf(z)
}

fn normal_cdf(z: f64) -> f64 {
    let a1 = 0.254829592;
    let a2 = -0.284496736;
    let a3 = 1.421413741;
    let a4 = -1.453152027;
    let a5 = 1.061405429;
    let p = 0.3275911;
    let sign = if z < 0.0 { -1.0 } else { 1.0 };
    let z = z.abs() / 10.0;
    let t = 1.0 / (1.0 + p * z);
    let y = 1.0 - (((((a5 * t + a4) * t) + a3) * t + a2) * t + a1) * t * (-z * z).exp();
    0.5 * (1.0 + sign * y)
}

/// Runs test (above/below median) for autocorrelation.
fn runs_test(data: &[u8]) -> f64 {
    if data.is_empty() {
        return 0.0;
    }
    let median = median_u8(data);
    let mut prev: Option<bool> = None;
    let mut runs: Vec<bool> = Vec::new();
    for &b in data {
        let cur = if b > median {
            Some(true)
        } else if b < median {
            Some(false)
        } else {
            prev
        };
        match (prev, cur) {
            (Some(p), Some(c)) if p != c => {
                runs.push(c);
                prev = Some(c);
            }
            (None, Some(c)) => {
                runs.push(c);
                prev = Some(c);
            }
            _ => {}
        }
    }
    let n1 = runs.iter().filter(|&&r| r).count();
    let n2 = runs.len() - n1;
    let r = runs.len();
    if n1 == 0 || n2 == 0 || r < 2 {
        return 0.0;
    }
    let expected = 2.0 * n1 as f64 * n2 as f64 / (r as f64) + 1.0;
    let var = 2.0 * n1 as f64 * n2 as f64 * (2.0 * n1 as f64 * n2 as f64 - n1 as f64 - n2 as f64)
        / ((r as f64).powi(2) * (r as f64 - 1.0));
    if var <= 0.0 {
        return 0.0;
    }
    (r as f64 - expected) / var.sqrt()
}

fn median_u8(data: &[u8]) -> u8 {
    let mut sorted = data.to_vec();
    sorted.sort_unstable();
    sorted[sorted.len() / 2]
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn validate_capped_at_1000() {
        let s = Sequencer;
        assert!(s
            .validate(&SeqPlan {
                method: "GET".into(),
                url: "http://example.com/".into(),
                count: 1_001,
                concurrency: 4,
                transport: Transport::Header {
                    name: "X-Seq".into()
                },
                generator: Generator::Uuid,
            })
            .is_err());
        assert!(s
            .validate(&SeqPlan {
                method: "GET".into(),
                url: "http://example.com/".into(),
                count: 1_000,
                concurrency: 4,
                transport: Transport::Header {
                    name: "X-Seq".into()
                },
                generator: Generator::Uuid,
            })
            .is_ok());
    }

    #[test]
    fn entropy_of_random_is_high() {
        let mut data = vec![0u8; 1024];
        for b in &mut data {
            *b = rand::random();
        }
        let obs = compute_observations_from_bytes(&data);
        assert!(obs.entropy_bits_per_byte > 7.5);
        assert!(obs.max_entropy_bits_per_byte >= 8.0);
    }

    #[test]
    fn entropy_of_constant_is_zero() {
        let data = vec![0xAAu8; 256];
        let obs = compute_observations_from_bytes(&data);
        assert!((obs.entropy_bits_per_byte - 0.0).abs() < 1e-9);
    }

    #[test]
    fn collision_count_is_zero_for_uuids() {
        let values: Vec<String> = (0..64)
            .map(|i| {
                let u = Uuid::from_u128(i as u128);
                base64::Engine::encode(&base64::engine::general_purpose::STANDARD, u.as_bytes())
            })
            .collect();
        let collected: Vec<ObservedValue> = values
            .iter()
            .map(|v| ObservedValue {
                value: v.clone(),
                status: 200,
                response_b64: "x".to_string(),
            })
            .collect();
        let obs = compute_observations(&collected);
        assert_eq!(obs.collisions, 0);
        assert_eq!(obs.distinct_values, 64);
    }

    fn compute_observations_from_bytes(data: &[u8]) -> Observations {
        let collected: Vec<ObservedValue> = data
            .iter()
            .map(|b| ObservedValue {
                value: base64::Engine::encode(&base64::engine::general_purpose::STANDARD, &[*b]),
                status: 200,
                response_b64: "x".to_string(),
            })
            .collect();
        compute_observations(&collected)
    }
}
